[build-system]
build-backend = 'mesonpy'
requires = ['meson-python', 'pyyaml', 'pybind11']

[project]
name = 'libcamera'
version = '0.1.0a1'
description = 'libcamera python bindings'
readme = 'README.md'

[project.urls]
Source = "https://github.com/will-v-pi/pylibcamera"
libcamera = "https://git.libcamera.org/libcamera/libcamera.git"

[tool.meson-python.args]
setup = [
    '-Drevision=v0.1.0'
]
