[build-system]
build-backend = 'mesonpy'
requires = ['meson-python', 'pyyaml', 'pybind11']

[project]
name = 'rpi-libcamera'
version = '0.0.5'
description = 'libcamera python bindings'
readme = 'README.md'

[project.urls]
Source = "https://github.com/will-v-pi/pylibcamera"
"RPi libcamera Source" = "https://github.com/raspberrypi/libcamera.git"

[tool.meson-python.args]
setup = [
    '-Drevision=release-v0.0.5+83-bde9b04f',
    '-Drepository=https://github.com/raspberrypi/libcamera.git'
]

[tool.flit.module]
name = "libcamera"
