[build-system]
build-backend = 'mesonpy'
requires = ['meson-python', 'pyyaml', 'pybind11']

[project]
name = 'libcamera'
version = '0.1.0'
description = 'Libcamera python bindings'

[tool.meson-python.args]
setup = [
    '-Drevision=v0.1.0'
]
