[build-system]
build-backend = 'mesonpy'
requires = ['meson-python', 'pyyaml', 'pybind11']

[project]
name = 'rpi-libcamera'
version = '0.1a1'
description = 'libcamera python bindings'
readme = 'README.md'

[project.urls]
Source = "https://github.com/will-v-pi/pylibcamera"
"RPi libcamera Source" = "https://github.com/raspberrypi/libcamera.git"

[tool.meson-python.args]
setup = [
    '-Drevision=17d88f4',
    '-Drepository=https://github.com/will-v-pi/libcamera.git',
    '-Dversion=v0.1.0+99-4a23664b'
]

[tool.flit.module]
name = "libcamera"
